version: "3.8"
services:
    bot:
        build: .
        env_file: .env
        restart: unless-stopped
    redis:
        image: valkey/valkey:8-alpine
        restart: unless-stopped
        healthcheck:
            test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
            start_period: 20s
            interval: 30s
            retries: 5
            timeout: 3s
        volumes:
            - ./volumes/redis:/data
