version: "3.8"
services:

    radia:
        build: .
        env_file: .env
        restart: unless-stopped

    postgresql:
        image: postgres
        restart: unless-stopped
        volumes:
            - ./var/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: "${POSTGRES}"
