version: "3.8"
services:

    radia:
        build: .
        restart: unless-stopped

    postgresql:
        image: postgres
        restart: unless-stopped
        volumes:
            - ./var/lib/postgresql/data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: "${postgres}"
